task:
  grpc:
    host: localhost
    port: 7080


server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/pinit_notification?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # dev: update, create-drop / prod: validate 추천
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

path:
  key:
    firebase: ${HOME}/pinit/keys/pinit-firebase-key.json